[env:steami]
platform = ststm32@^19
board = nucleo_wb55rg_p
framework = arduino
monitor_speed = 115200

; OpenOCD + cmsis-dap compile OK here, but upload may fail with some DAPLink probes.
; Default to drag-and-drop upload via the DAPLINK mass-storage drive.
upload_protocol = custom
upload_command = ${PROJECT_DIR}/scripts/upload_daplink.sh $SOURCE

build_flags =
  -DSTEAMI_BOARD
  -DPIN_LED_RED=PC12
  -DPIN_LED_GREEN=PC11
  -DPIN_LED_BLUE=PC10
  -DPIN_SERIAL_RX=PB10
  -DPIN_SERIAL_TX=PB11
