[env:steami]
platform = ststm32@^19
board = steami
board_build.variants_dir = variants
framework = arduino
monitor_speed = 115200

upload_protocol = custom
upload_command = ${PROJECT_DIR}/scripts/upload_daplink.sh $SOURCE
