[platformio]
default_envs = steami
test_dir = tests

[env:steami]
platform = ststm32@^19
board = steami
framework = arduino
monitor_speed = 115200
test_framework = unity
test_filter =
  hardware/test_*
  integration/test_*
build_flags =
  -I tests/shared

[env:native]
platform = native
test_framework = unity
test_filter = native/test_*
lib_compat_mode = off
build_flags =
  -std=c++17
  -D UNIT_TEST
  -I tests/native/helpers
  -I tests/shared
