name: Clang Format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run formatting check
        run: make lint
